// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160, Result } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from 'dedot/contracts';
import type { TrustGraphError, InkPrimitivesLangError } from './types.js';

export interface ContractQuery<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractQuery<ChainApi, Type> {
  /**
   * Setter functions for adding/deleting trusted addresses
   *
   * @param {H160} newTrusted
   * @param {ContractCallOptions} options
   *
   * @selector 0xded740e1
   **/
  setNewTrusted: GenericContractQueryCall<
    ChainApi,
    (
      newTrusted: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], TrustGraphError>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {H160} toDelete
   * @param {ContractCallOptions} options
   *
   * @selector 0x18a53640
   **/
  deleteTrusted: GenericContractQueryCall<
    ChainApi,
    (
      toDelete: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], TrustGraphError>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Getter function for getting trusted addresses
   *
   * @param {H160} lender
   * @param {ContractCallOptions} options
   *
   * @selector 0x539b9b1c
   **/
  getAllTrusted: GenericContractQueryCall<
    ChainApi,
    (
      lender: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<Array<H160>, TrustGraphError>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {H160} lender
   * @param {H160} borrower
   * @param {ContractCallOptions} options
   *
   * @selector 0x651da7b8
   **/
  isTrusted: GenericContractQueryCall<
    ChainApi,
    (
      lender: H160,
      borrower: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult<ChainApi>>>,
    Type
  >;
}
