// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160 } from 'dedot/codecs';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ContractTx<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractTx<ChainApi, Type> {
  /**
   * Setter functions for adding/deleting trusted addresses
   *
   * @param {H160} newTrusted
   * @param {ContractTxOptions} options
   *
   * @selector 0xded740e1
   **/
  setNewTrusted: GenericContractTxCall<
    ChainApi,
    (newTrusted: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   *
   * @param {H160} toDelete
   * @param {ContractTxOptions} options
   *
   * @selector 0x18a53640
   **/
  deleteTrusted: GenericContractTxCall<
    ChainApi,
    (toDelete: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
