// Generated by dedot cli

import type { H160 } from 'dedot/codecs';

export type InkStorageLazyMapping = {};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type TrustGraph = { trusted: { get(arg: H160): Promise<Array<H160> | undefined> } };

export type InkPrimitivesLangError = 'CouldNotReadInput';

export type TrustGraphError = 'NoTrustedAddresses' | 'NotTrusted';
