// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160 } from 'dedot/codecs';
import type { GenericContractEvents, GenericContractEvent, MetadataType } from 'dedot/contracts';
import type { TrustOracleEventKind } from './types.js';

export interface ContractEvents<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractEvents<ChainApi, Type> {
  /**
   * Evento on-chain (no se guarda como Vec en storage, solo logs).
   *
   *
   **/
  TrustEventRecorded: GenericContractEvent<
    'TrustEventRecorded',
    {
      /**
       *
       * @indexed: true
       **/
      borrower: H160;
      /**
       *
       * @indexed: false
       **/
      kind: TrustOracleEventKind;
      /**
       *
       * @indexed: false
       **/
      amount: bigint | undefined;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
      /**
       *
       * @indexed: false
       **/
      newScore: number;
    },
    Type
  >;
}
