// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result, H160 } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from 'dedot/contracts';
import type { InkPrimitivesLangError, TrustOracleRole } from './types.js';

export interface ContractQuery<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractQuery<ChainApi, Type> {
  /**
   * Cambiar pesos de scoring. Si el caller no es owner, no hace nada.
   *
   * @param {number} installmentPaidWeight
   * @param {number} missedPaymentWeight
   * @param {number} guarantorAddedWeight
   * @param {number} identityVerifiedWeight
   * @param {ContractCallOptions} options
   *
   * @selector 0x92402873
   **/
  setWeights: GenericContractQueryCall<
    ChainApi,
    (
      installmentPaidWeight: number,
      missedPaymentWeight: number,
      guarantorAddedWeight: number,
      identityVerifiedWeight: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Autorizar un contrato para registrar eventos de trust.
   *
   * @param {H160} account
   * @param {ContractCallOptions} options
   *
   * @selector 0x21fc7b67
   **/
  authorizeCaller: GenericContractQueryCall<
    ChainApi,
    (
      account: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Revocar autorización.
   *
   * @param {H160} account
   * @param {ContractCallOptions} options
   *
   * @selector 0x3f54b558
   **/
  revokeCaller: GenericContractQueryCall<
    ChainApi,
    (
      account: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Consultar el rol de una cuenta (owner, authorized o ninguno).
   *
   * @param {H160} account
   * @param {ContractCallOptions} options
   *
   * @selector 0x85f65d55
   **/
  getRole: GenericContractQueryCall<
    ChainApi,
    (
      account: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<TrustOracleRole | undefined, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Obtener el owner actual.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x07fcd0b1
   **/
  getOwner: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<H160, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Registrar pago (cuota o pago adaptativo).
   *
   * @param {H160} borrower
   * @param {bigint} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0xf1f31979
   **/
  recordInstallmentPaid: GenericContractQueryCall<
    ChainApi,
    (
      borrower: H160,
      amount: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Registrar falta de pago.
   *
   * @param {H160} borrower
   * @param {ContractCallOptions} options
   *
   * @selector 0xb1b9e28b
   **/
  recordMissedPayment: GenericContractQueryCall<
    ChainApi,
    (
      borrower: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Registrar que se agregó un garante.
   *
   * @param {H160} borrower
   * @param {ContractCallOptions} options
   *
   * @selector 0x3d5e39d2
   **/
  recordGuarantorAdded: GenericContractQueryCall<
    ChainApi,
    (
      borrower: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Registrar verificación de identidad (KYC, DID, etc.).
   *
   * @param {H160} borrower
   * @param {ContractCallOptions} options
   *
   * @selector 0xbea22b33
   **/
  recordIdentityVerified: GenericContractQueryCall<
    ChainApi,
    (
      borrower: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Obtener trust score actual de un borrower.
   *
   * @param {H160} borrower
   * @param {ContractCallOptions} options
   *
   * @selector 0xf4e8b926
   **/
  getTrustScore: GenericContractQueryCall<
    ChainApi,
    (
      borrower: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Obtener pesos de scoring (útil para frontend / debug).
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x786b8100
   **/
  getWeights: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<[number, number, number, number], ContractCallResult<ChainApi>>>,
    Type
  >;
}
