// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160 } from 'dedot/codecs';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ContractTx<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractTx<ChainApi, Type> {
  /**
   * Cambiar pesos de scoring. Si el caller no es owner, no hace nada.
   *
   * @param {number} installmentPaidWeight
   * @param {number} missedPaymentWeight
   * @param {number} guarantorAddedWeight
   * @param {number} identityVerifiedWeight
   * @param {ContractTxOptions} options
   *
   * @selector 0x92402873
   **/
  setWeights: GenericContractTxCall<
    ChainApi,
    (
      installmentPaidWeight: number,
      missedPaymentWeight: number,
      guarantorAddedWeight: number,
      identityVerifiedWeight: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Autorizar un contrato para registrar eventos de trust.
   *
   * @param {H160} account
   * @param {ContractTxOptions} options
   *
   * @selector 0x21fc7b67
   **/
  authorizeCaller: GenericContractTxCall<
    ChainApi,
    (account: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Revocar autorización.
   *
   * @param {H160} account
   * @param {ContractTxOptions} options
   *
   * @selector 0x3f54b558
   **/
  revokeCaller: GenericContractTxCall<
    ChainApi,
    (account: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Registrar pago (cuota o pago adaptativo).
   *
   * @param {H160} borrower
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0xf1f31979
   **/
  recordInstallmentPaid: GenericContractTxCall<
    ChainApi,
    (borrower: H160, amount: bigint, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Registrar falta de pago.
   *
   * @param {H160} borrower
   * @param {ContractTxOptions} options
   *
   * @selector 0xb1b9e28b
   **/
  recordMissedPayment: GenericContractTxCall<
    ChainApi,
    (borrower: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Registrar que se agregó un garante.
   *
   * @param {H160} borrower
   * @param {ContractTxOptions} options
   *
   * @selector 0x3d5e39d2
   **/
  recordGuarantorAdded: GenericContractTxCall<
    ChainApi,
    (borrower: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Registrar verificación de identidad (KYC, DID, etc.).
   *
   * @param {H160} borrower
   * @param {ContractTxOptions} options
   *
   * @selector 0xbea22b33
   **/
  recordIdentityVerified: GenericContractTxCall<
    ChainApi,
    (borrower: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
