// Generated by dedot cli

import type { H160 } from 'dedot/codecs';

export type InkStorageLazyMapping = {};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type TrustOracle = {
  owner: H160;
  scores: { get(arg: H160): Promise<number | undefined> };
  installmentPaidWeight: number;
  missedPaymentWeight: number;
  guarantorAddedWeight: number;
  identityVerifiedWeight: number;
  authorizedCallers: { get(arg: H160): Promise<[] | undefined> };
};

export type InkPrimitivesLangError = 'CouldNotReadInput';

export type TrustOracleRole = 'Owner' | 'Authorized';

export type TrustOracleEventKind = 'InstallmentPaid' | 'MissedPayment' | 'GuarantorAdded' | 'IdentityVerified';
