// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Hash, H160 } from 'dedot/codecs';
import type { GenericContractEvents, GenericContractEvent, MetadataType } from 'dedot/contracts';

export interface ContractEvents<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractEvents<ChainApi, Type> {
  /**
   *
   *
   **/
  LoanEnded: GenericContractEvent<
    'LoanEnded',
    {
      /**
       *
       * @indexed: false
       **/
      loanId: Hash;
    },
    Type
  >;

  /**
   *
   *
   **/
  LoanFunded: GenericContractEvent<
    'LoanFunded',
    {
      /**
       *
       * @indexed: false
       **/
      loanId: Hash;
      /**
       *
       * @indexed: false
       **/
      lender: H160;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  LoanRepaid: GenericContractEvent<
    'LoanRepaid',
    {
      /**
       *
       * @indexed: false
       **/
      loanId: Hash;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
    },
    Type
  >;

  /**
   * Events for the loans lifecycle
   *
   *
   **/
  LoanCreated: GenericContractEvent<
    'LoanCreated',
    {
      /**
       *
       * @indexed: false
       **/
      loanId: Hash;
      /**
       *
       * @indexed: false
       **/
      borrower: H160;
    },
    Type
  >;

  /**
   *
   *
   **/
  LoanActivated: GenericContractEvent<
    'LoanActivated',
    {
      /**
       *
       * @indexed: false
       **/
      loanId: Hash;
      /**
       *
       * @indexed: false
       **/
      borrower: H160;
    },
    Type
  >;

  /**
   *
   *
   **/
  LoanDefaulted: GenericContractEvent<
    'LoanDefaulted',
    {
      /**
       *
       * @indexed: false
       **/
      loanId: Hash;
    },
    Type
  >;
}
