// Generated by dedot cli

import type { VersionedGenericSubstrateApi, RpcVersion, RpcV2 } from 'dedot/types';
import type { InkGenericContractApi, WithLazyStorage } from 'dedot/contracts';
import type { SubstrateApi } from 'dedot/chaintypes';
import type { InkPrimitivesLangError, LoanManager } from './types.js';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';

export * from './types.js';

/**
 * @name: LoanManagerContractApi
 * @contractName: loan_manager
 * @contractVersion: 0.1.0
 * @authors: Fabian Sanchez <fabiansanchezd@outlook.com>
 * @language: ink! 6.0.0-beta.1
 **/
export interface LoanManagerContractApi<
  Rv extends RpcVersion = RpcVersion,
  ChainApi extends VersionedGenericSubstrateApi = SubstrateApi,
> extends InkGenericContractApi<Rv, ChainApi> {
  metadataType: 'ink';
  query: ContractQuery<ChainApi[Rv], 'ink'>;
  tx: ContractTx<ChainApi[Rv], 'ink'>;
  constructorQuery: ConstructorQuery<ChainApi[Rv], 'ink'>;
  constructorTx: ConstructorTx<ChainApi[Rv], LoanManagerContractApi, 'ink'>;
  events: ContractEvents<ChainApi[Rv], 'ink'>;
  storage: {
    root(): Promise<LoanManager>;
    lazy(): WithLazyStorage<LoanManager>;
  };

  types: {
    ChainApi: ChainApi[Rv];
    RootStorage: LoanManager;
    LazyStorage: WithLazyStorage<LoanManager>;
    LangError: InkPrimitivesLangError;
  };
}
