// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like, Result, H160 } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type {
  LoanManagerError,
  InkPrimitivesLangError,
  LoanManagerLoan,
} from "./types.js";

export interface ContractQuery<
  Type extends MetadataType,
> extends GenericContractQuery<Type> {
  /**
   * Request a loan from the lending pool
   * Creates a pending loan that requires vouches before disbursement
   *
   * @param {bigint} amount
   * @param {bigint} loanTerm
   * @param {AccountId32Like} accountId
   * @param {ContractCallOptions} options
   *
   * @selector 0x3177501d
   **/
  requestLoan: GenericContractQueryCall<
    (
      amount: bigint,
      loanTerm: bigint,
      accountId: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<bigint, LoanManagerError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   *
   * @param {bigint} loanId
   * @param {number} stars
   * @param {number} capitalPercent
   * @param {AccountId32Like} voucherAccountId
   * @param {H160} loanManagerAddress
   * @param {ContractCallOptions} options
   *
   * @selector 0xdeb14168
   **/
  vouchForLoan: GenericContractQueryCall<
    (
      loanId: bigint,
      stars: number,
      capitalPercent: number,
      voucherAccountId: AccountId32Like,
      loanManagerAddress: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LoanManagerError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   *
   * @param {bigint} loanId
   * @param {ContractCallOptions} options
   *
   * @selector 0xec37df47
   **/
  getLoan: GenericContractQueryCall<
    (
      loanId: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<LoanManagerLoan | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} loanId
   * @param {AccountId32Like} borrowerAccountId
   * @param {H160} loanManagerAddress
   * @param {ContractCallOptions} options
   *
   * @selector 0x2a01c432
   **/
  repayLoan: GenericContractQueryCall<
    (
      loanId: bigint,
      borrowerAccountId: AccountId32Like,
      loanManagerAddress: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LoanManagerError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Check if a loan is overdue and handle defaulting
   *
   * This function can be called by anyone to trigger default processing for overdue loans.
   * It includes safeguards to prevent premature defaults:
   * - Only active loans can be defaulted (prevents double-processing)
   * - Loan must be past due date + grace period (configurable buffer)
   *
   * The grace period provides a buffer after the due date, allowing borrowers time to
   * repay and preventing race conditions with repayment transactions.
   *
   * Slashes borrower's stars and resolves vouches as failed
   *
   * @param {bigint} loanId
   * @param {H160} loanManagerAddress
   * @param {H160} vouchContractAddress
   * @param {ContractCallOptions} options
   *
   * @selector 0x711f1285
   **/
  checkDefault: GenericContractQueryCall<
    (
      loanId: bigint,
      loanManagerAddress: H160,
      vouchContractAddress: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], LoanManagerError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Get the repayment amount for a loan
   * Returns the fixed repayment amount (principal + interest) calculated at loan creation
   * Returns value in 18 decimals (chain format) for consistency with total liquidity
   *
   * @param {bigint} loanId
   * @param {ContractCallOptions} options
   *
   * @selector 0xc37cebb4
   **/
  getRepaymentAmount: GenericContractQueryCall<
    (
      loanId: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<bigint, LoanManagerError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Get all pending loans
   * Returns a vector of loan IDs that are currently pending
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xa64be167
   **/
  getAllPendingLoans: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<bigint>, ContractCallResult>>,
    Type
  >;

  /**
   * Get all active loans
   * Returns a vector of loan IDs that are currently active
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xe3c98be0
   **/
  getAllActiveLoans: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<bigint>, ContractCallResult>>,
    Type
  >;
}
