// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Hash, Result, H160 } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from 'dedot/contracts';
import type { LoanManagerError, InkPrimitivesLangError, LoanManagerLoan } from './types.js';

export interface ContractQuery<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractQuery<ChainApi, Type> {
  /**
   * Creates a loan request, with caller being the borrower
   * The borrower must have at least one trusted address in their TrustGraph
   *
   * @param {bigint} requestedAmount
   * @param {bigint} duration
   * @param {ContractCallOptions} options
   *
   * @selector 0x36469ae4
   **/
  createLoan: GenericContractQueryCall<
    ChainApi,
    (
      requestedAmount: bigint,
      duration: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<Hash, LoanManagerError>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Lenders can lend to a loan by sending funds into it
   * The lender must trust the borrower in their TrustGraph
   *
   * @param {Hash} loanId
   * @param {ContractCallOptions} options
   *
   * @selector 0x7b59dea2
   **/
  fundLoan: GenericContractQueryCall<
    ChainApi,
    (
      loanId: Hash,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], LoanManagerError>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Borrower can pay back their loan partially or fully
   *
   * @param {Hash} loanId
   * @param {ContractCallOptions} options
   *
   * @selector 0xe36ebe8c
   **/
  payLoan: GenericContractQueryCall<
    ChainApi,
    (
      loanId: Hash,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], LoanManagerError>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Check and mark loan as defaulted if overdue and not repaid
   *
   * @param {Hash} loanId
   * @param {ContractCallOptions} options
   *
   * @selector 0x711f1285
   **/
  checkDefault: GenericContractQueryCall<
    ChainApi,
    (
      loanId: Hash,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], LoanManagerError>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Getter functions for frontend
   *
   * @param {H160} borrower
   * @param {ContractCallOptions} options
   *
   * @selector 0x62af3bd0
   **/
  getUserLoans: GenericContractQueryCall<
    ChainApi,
    (
      borrower: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<Hash>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {Hash} loanId
   * @param {ContractCallOptions} options
   *
   * @selector 0xec37df47
   **/
  getLoan: GenericContractQueryCall<
    ChainApi,
    (
      loanId: Hash,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<LoanManagerLoan | undefined, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractCallOptions} options
   *
   * @selector 0x8a24ad50
   **/
  getCreditScore: GenericContractQueryCall<
    ChainApi,
    (
      addr: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Get all loans from trusted borrowers that are pending funding
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x010076ad
   **/
  getTrustedLoans: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<LoanManagerLoan>, ContractCallResult<ChainApi>>>,
    Type
  >;
}
