// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Hash } from 'dedot/codecs';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ContractTx<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractTx<ChainApi, Type> {
  /**
   * Creates a loan request, with caller being the borrower
   * The borrower must have at least one trusted address in their TrustGraph
   *
   * @param {bigint} requestedAmount
   * @param {bigint} duration
   * @param {ContractTxOptions} options
   *
   * @selector 0x36469ae4
   **/
  createLoan: GenericContractTxCall<
    ChainApi,
    (requestedAmount: bigint, duration: bigint, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Lenders can lend to a loan by sending funds into it
   * The lender must trust the borrower in their TrustGraph
   *
   * @param {Hash} loanId
   * @param {ContractTxOptions} options
   *
   * @selector 0x7b59dea2
   **/
  fundLoan: GenericContractTxCall<
    ChainApi,
    (loanId: Hash, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Borrower can pay back their loan partially or fully
   *
   * @param {Hash} loanId
   * @param {ContractTxOptions} options
   *
   * @selector 0xe36ebe8c
   **/
  payLoan: GenericContractTxCall<
    ChainApi,
    (loanId: Hash, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Check and mark loan as defaulted if overdue and not repaid
   *
   * @param {Hash} loanId
   * @param {ContractTxOptions} options
   *
   * @selector 0x711f1285
   **/
  checkDefault: GenericContractTxCall<
    ChainApi,
    (loanId: Hash, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
