// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like, H160 } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";

export interface ContractTx<
  Type extends MetadataType,
> extends GenericContractTx<Type> {
  /**
   * Request a loan from the lending pool
   * Creates a pending loan that requires vouches before disbursement
   *
   * @param {bigint} amount
   * @param {bigint} loanTerm
   * @param {AccountId32Like} accountId
   * @param {ContractTxOptions} options
   *
   * @selector 0x3177501d
   **/
  requestLoan: GenericContractTxCall<
    (
      amount: bigint,
      loanTerm: bigint,
      accountId: AccountId32Like,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} loanId
   * @param {number} stars
   * @param {number} capitalPercent
   * @param {AccountId32Like} voucherAccountId
   * @param {H160} loanManagerAddress
   * @param {ContractTxOptions} options
   *
   * @selector 0xdeb14168
   **/
  vouchForLoan: GenericContractTxCall<
    (
      loanId: bigint,
      stars: number,
      capitalPercent: number,
      voucherAccountId: AccountId32Like,
      loanManagerAddress: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} loanId
   * @param {AccountId32Like} borrowerAccountId
   * @param {H160} loanManagerAddress
   * @param {ContractTxOptions} options
   *
   * @selector 0x2a01c432
   **/
  repayLoan: GenericContractTxCall<
    (
      loanId: bigint,
      borrowerAccountId: AccountId32Like,
      loanManagerAddress: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Check if a loan is overdue and handle defaulting
   *
   * This function can be called by anyone to trigger default processing for overdue loans.
   * It includes safeguards to prevent premature defaults:
   * - Only active loans can be defaulted (prevents double-processing)
   * - Loan must be past due date + grace period (configurable buffer)
   *
   * The grace period provides a buffer after the due date, allowing borrowers time to
   * repay and preventing race conditions with repayment transactions.
   *
   * Slashes borrower's stars and resolves vouches as failed
   *
   * @param {bigint} loanId
   * @param {H160} loanManagerAddress
   * @param {H160} vouchContractAddress
   * @param {ContractTxOptions} options
   *
   * @selector 0x711f1285
   **/
  checkDefault: GenericContractTxCall<
    (
      loanId: bigint,
      loanManagerAddress: H160,
      vouchContractAddress: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;
}
