// Generated by dedot cli

import type { Hash, H160 } from 'dedot/codecs';

export type InkStorageLazyMapping = {};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type LoanManagerLoan = {
  loanId: Hash;
  borrower: H160;
  requestedAmount: bigint;
  fundedAmount: bigint;
  lenderCount: number;
  interestRate: bigint;
  penaltyRate: bigint;
  duration: bigint;
  startTime: bigint;
  dueTime: bigint;
  repaidAmount: bigint;
  status: LoanManagerLoanStatus;
  reserve: bigint;
};

export type LoanManagerLoanStatus = 'Pending' | 'Active' | 'Repaid' | 'Defaulted';

export type LoanManager = {
  configAddress: H160;
  trustGraphAddress: H160;
  creditScore: { get(arg: H160): Promise<number | undefined> };
  loans: { get(arg: Hash): Promise<LoanManagerLoan | undefined> };
  borrowerLoans: { get(arg: H160): Promise<Array<Hash> | undefined> };
  lenders: { get(arg: [Hash, H160]): Promise<bigint | undefined> };
};

export type InkPrimitivesLangError = 'CouldNotReadInput';

export type LoanManagerError =
  | 'NotTrusted'
  | 'LoanNotFound'
  | 'InvalidDuration'
  | 'InsufficientOverfunding'
  | 'NotEnoughLenders'
  | 'Unauthorized'
  | 'LoanNotPending'
  | 'LoanNotActive'
  | 'Overdue'
  | 'InsufficientPayment'
  | 'CrossContractCallFailed'
  | 'TransferFailed'
  | 'ZeroAmount'
  | 'AlreadyDefaulted';
