// Generated by dedot cli

import type { AccountId32, H160 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type LoanManagerLoan = {
  loanId: bigint;
  interestRate: bigint;
  term: bigint;
  startTime: bigint;
  amount: bigint;
  borrower: AccountId32;
  status: LoanManagerLoanStatus;
  totalRepaymentAmount: bigint;
};

export type LoanManagerLoanStatus =
  | "Pending"
  | "Active"
  | "Repaid"
  | "Defaulted";

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type LoanManager = {
  config: H160;
  reputation: H160;
  lendingPool: H160;
  vouch: H160;
  lendingPoolAddress: H160;
  loans: { get(arg: bigint): Promise<LoanManagerLoan | undefined> };
  nextLoanId: bigint;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type LoanManagerError =
  | "InsufficientReputation"
  | "InsufficientVouches"
  | "ZeroAmount"
  | "DisbursementFailed"
  | "LoanNotFound"
  | "LoanNotActive"
  | "LoanNotPending"
  | "LoanNotOverdue"
  | "SlashFailed"
  | "ResolveFailed"
  | "Unauthorized"
  | "RepaymentFailed"
  | "InvalidRepaymentAmount"
  | "Overflow";
