// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160, Result } from 'dedot/codecs';
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
  MetadataType,
} from 'dedot/contracts';
import type { InkPrimitivesLangError } from './types.js';

export interface ConstructorQuery<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericConstructorQuery<ChainApi, Type> {
  /**
   * Crea un nuevo LoanRegistry.
   *
   * - `trust_oracle`: dirección del contrato TrustOracle.
   * - `min_trust_score`: mínimo score requerido para crear loans.
   *
   * @param {H160} trustOracle
   * @param {number} minTrustScore
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    ChainApi,
    (
      trustOracle: H160,
      minTrustScore: number,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult<ChainApi>>>,
    Type
  >;
}
