// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160 } from 'dedot/codecs';
import type {
  GenericConstructorTx,
  GenericConstructorTxCall,
  ConstructorTxOptions,
  InkGenericContractApi,
  GenericInstantiateSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ConstructorTx<
  ChainApi extends GenericSubstrateApi,
  ContractApi extends InkGenericContractApi,
  Type extends MetadataType,
> extends GenericConstructorTx<ChainApi, Type> {
  /**
   * Crea un nuevo LoanRegistry.
   *
   * - `trust_oracle`: dirección del contrato TrustOracle.
   * - `min_trust_score`: mínimo score requerido para crear loans.
   *
   * @param {H160} trustOracle
   * @param {number} minTrustScore
   * @param {ConstructorTxOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorTxCall<
    ChainApi,
    (
      trustOracle: H160,
      minTrustScore: number,
      options?: ConstructorTxOptions,
    ) => GenericInstantiateSubmittableExtrinsic<ChainApi, ContractApi>,
    Type
  >;
}
