// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160 } from 'dedot/codecs';
import type { GenericContractEvents, GenericContractEvent, MetadataType } from 'dedot/contracts';

export interface ContractEvents<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractEvents<ChainApi, Type> {
  /**
   * Evento: se actualiza la dirección del TrustOracle.
   *
   *
   **/
  TrustOracleUpdated: GenericContractEvent<
    'TrustOracleUpdated',
    {
      /**
       *
       * @indexed: false
       **/
      old: H160;
      /**
       *
       * @indexed: false
       **/
      new: H160;
    },
    Type
  >;

  /**
   * Evento: se actualiza el mínimo trust score.
   *
   *
   **/
  MinTrustScoreUpdated: GenericContractEvent<
    'MinTrustScoreUpdated',
    {
      /**
       *
       * @indexed: false
       **/
      old: number;
      /**
       *
       * @indexed: false
       **/
      new: number;
    },
    Type
  >;

  /**
   * Evento: se crea un nuevo préstamo.
   *
   *
   **/
  LoanCreated: GenericContractEvent<
    'LoanCreated',
    {
      /**
       *
       * @indexed: true
       **/
      borrower: H160;
      /**
       *
       * @indexed: true
       **/
      loanAddress: H160;
      /**
       *
       * @indexed: false
       **/
      principal: bigint;
      /**
       *
       * @indexed: false
       **/
      overfactorBps: number;
    },
    Type
  >;
}
