// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result, H160 } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from 'dedot/contracts';
import type { InkPrimitivesLangError } from './types.js';

export interface ContractQuery<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractQuery<ChainApi, Type> {
  /**
   * Actualiza el mínimo trust score requerido.
   * Solo el owner puede cambiarlo.
   *
   * @param {number} newMin
   * @param {ContractCallOptions} options
   *
   * @selector 0x80097278
   **/
  setMinTrustScore: GenericContractQueryCall<
    ChainApi,
    (
      newMin: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Actualiza la dirección del TrustOracle.
   * Solo el owner puede cambiarla.
   *
   * @param {H160} addr
   * @param {ContractCallOptions} options
   *
   * @selector 0x4244589c
   **/
  setTrustOracle: GenericContractQueryCall<
    ChainApi,
    (addr: H160, options?: ContractCallOptions) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Crea un nuevo loan para el caller (borrower).
   *
   * Requisitos:
   * - `trust_oracle.get_trust_score(borrower) >= min_trust_score`
   *
   * Por ahora:
   * - Genera una dirección pseudo-única para el loan (placeholder).
   * - La idea es reemplazar esto por la address real del contrato `loan_instance`
   * cuando tengamos el tipo de referencia correcto.
   *
   * @param {bigint} principal
   * @param {number} overfactorBps
   * @param {bigint} maxDuration
   * @param {ContractCallOptions} options
   *
   * @selector 0x36469ae4
   **/
  createLoan: GenericContractQueryCall<
    ChainApi,
    (
      principal: bigint,
      overfactorBps: number,
      maxDuration: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<H160, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Devuelve la lista global de todos los loans.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xa8b86953
   **/
  getAllLoans: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<Array<H160>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Devuelve todos los loans creados por un borrower.
   *
   * @param {H160} borrower
   * @param {ContractCallOptions} options
   *
   * @selector 0xb0a91f4b
   **/
  getLoansByBorrower: GenericContractQueryCall<
    ChainApi,
    (
      borrower: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<H160>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Devuelve todos los loans donde una cuenta actúa como lender.
   *
   * Nota: por ahora este mapping no se mantiene;
   * se dejará para integración futura desde loan_instance.
   *
   * @param {H160} lender
   * @param {ContractCallOptions} options
   *
   * @selector 0xc2a968b8
   **/
  getLoansByLender: GenericContractQueryCall<
    ChainApi,
    (
      lender: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<H160>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Dirección actual del TrustOracle.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x6e8b7183
   **/
  getTrustOracle: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<H160, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Trust score mínimo requerido para crear loans.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x7d5069a9
   **/
  getMinTrustScore: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<number, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Devuelve el owner del registry.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x07fcd0b1
   **/
  getOwner: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<H160, ContractCallResult<ChainApi>>>,
    Type
  >;
}
