// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160 } from 'dedot/codecs';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ContractTx<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractTx<ChainApi, Type> {
  /**
   * Actualiza el mínimo trust score requerido.
   * Solo el owner puede cambiarlo.
   *
   * @param {number} newMin
   * @param {ContractTxOptions} options
   *
   * @selector 0x80097278
   **/
  setMinTrustScore: GenericContractTxCall<
    ChainApi,
    (newMin: number, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Actualiza la dirección del TrustOracle.
   * Solo el owner puede cambiarla.
   *
   * @param {H160} addr
   * @param {ContractTxOptions} options
   *
   * @selector 0x4244589c
   **/
  setTrustOracle: GenericContractTxCall<
    ChainApi,
    (addr: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   * Crea un nuevo loan para el caller (borrower).
   *
   * Requisitos:
   * - `trust_oracle.get_trust_score(borrower) >= min_trust_score`
   *
   * Por ahora:
   * - Genera una dirección pseudo-única para el loan (placeholder).
   * - La idea es reemplazar esto por la address real del contrato `loan_instance`
   * cuando tengamos el tipo de referencia correcto.
   *
   * @param {bigint} principal
   * @param {number} overfactorBps
   * @param {bigint} maxDuration
   * @param {ContractTxOptions} options
   *
   * @selector 0x36469ae4
   **/
  createLoan: GenericContractTxCall<
    ChainApi,
    (
      principal: bigint,
      overfactorBps: number,
      maxDuration: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
