// Generated by dedot cli

import type { H160 } from 'dedot/codecs';

export type InkStorageLazyMapping = {};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type LoanRegistry = {
  owner: H160;
  trustOracle: H160;
  loans: Array<H160>;
  borrowerLoans: { get(arg: H160): Promise<Array<H160> | undefined> };
  lenderLoans: { get(arg: H160): Promise<Array<H160> | undefined> };
  minTrustScore: number;
};

export type InkPrimitivesLangError = 'CouldNotReadInput';
