// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160, Result } from 'dedot/codecs';
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
  MetadataType,
} from 'dedot/contracts';
import type { InkPrimitivesLangError } from './types.js';

export interface ConstructorQuery<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericConstructorQuery<ChainApi, Type> {
  /**
   *
   * @param {H160} borrower
   * @param {bigint} principal
   * @param {number} overfactorBps
   * @param {bigint} maxDuration
   * @param {H160} trustOracle
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    ChainApi,
    (
      borrower: H160,
      principal: bigint,
      overfactorBps: number,
      maxDuration: bigint,
      trustOracle: H160,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult<ChainApi>>>,
    Type
  >;
}
