// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result, H160 } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from 'dedot/contracts';
import type { InkPrimitivesLangError, LoanInstanceLoanState, LoanInstanceLenderContribution } from './types.js';

export interface ContractQuery<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractQuery<ChainApi, Type> {
  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x9b3544d0
   **/
  contribute: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xa9f4b044
   **/
  repay: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {bigint} gracePeriod
   * @param {ContractCallOptions} options
   *
   * @selector 0x711f1285
   **/
  checkDefault: GenericContractQueryCall<
    ChainApi,
    (
      gracePeriod: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x3d1e8968
   **/
  getState: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<LoanInstanceLoanState, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x60a9203d
   **/
  getRemainingDebt: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<bigint, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xa55d54a1
   **/
  getContributions: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<LoanInstanceLenderContribution>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x44c8d3ba
   **/
  getBorrower: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<H160, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x8876f17c
   **/
  getPrincipal: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<bigint, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Antes era un flag de si el buffer fue depositado en Hydration.
   * Ahora simplemente indica si hay buffer retenido en el contrato.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x415c9c20
   **/
  getBufferDeposited: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult<ChainApi>>>,
    Type
  >;
}
