// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ContractTx<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractTx<ChainApi, Type> {
  /**
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x9b3544d0
   **/
  contribute: GenericContractTxCall<
    ChainApi,
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xa9f4b044
   **/
  repay: GenericContractTxCall<ChainApi, (options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>, Type>;

  /**
   *
   * @param {bigint} gracePeriod
   * @param {ContractTxOptions} options
   *
   * @selector 0x711f1285
   **/
  checkDefault: GenericContractTxCall<
    ChainApi,
    (gracePeriod: bigint, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
