// Generated by dedot cli

import type { H160 } from 'dedot/codecs';

export type LoanInstanceLenderContribution = { lender: H160; amount: bigint };

export type LoanInstance = {
  borrower: H160;
  principal: bigint;
  overfactorBps: number;
  totalRequired: bigint;
  totalContributed: bigint;
  minLenders: number;
  contributions: Array<LoanInstanceLenderContribution>;
  remainingDebt: bigint;
  state: LoanInstanceLoanState;
  createdAt: bigint;
  lastPaymentAt: bigint;
  trustOracle: H160;
  bufferAmount: bigint;
  trustScoreAtIssuance: number;
};

export type LoanInstanceLoanState = 'Funding' | 'Active' | 'Defaulted' | 'Completed';

export type InkPrimitivesLangError = 'CouldNotReadInput';
