// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericConstructorTx,
  GenericConstructorTxCall,
  ConstructorTxOptions,
  InkGenericContractApi,
  GenericInstantiateSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ConstructorTx<
  ChainApi extends GenericSubstrateApi,
  ContractApi extends InkGenericContractApi,
  Type extends MetadataType,
> extends GenericConstructorTx<ChainApi, Type> {
  /**
   * Constructor that initializes configuration of the Kleo Protocol
   *
   * @param {number} minLenders
   * @param {bigint} overfundingFactor
   * @param {bigint} baseInterestRate
   * @param {bigint} latePenaltyRate
   * @param {bigint} maxLoanDuration
   * @param {ConstructorTxOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorTxCall<
    ChainApi,
    (
      minLenders: number,
      overfundingFactor: bigint,
      baseInterestRate: bigint,
      latePenaltyRate: bigint,
      maxLoanDuration: bigint,
      options?: ConstructorTxOptions,
    ) => GenericInstantiateSubmittableExtrinsic<ChainApi, ContractApi>,
    Type
  >;
}
