// Generated by dedot cli

import type { VersionedGenericSubstrateApi, RpcVersion, RpcV2 } from 'dedot/types';
import type { InkGenericContractApi, WithLazyStorage } from 'dedot/contracts';
import type { SubstrateApi } from 'dedot/chaintypes';
import type { InkPrimitivesLangError, Config } from './types.js';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';

export * from './types.js';

/**
 * @name: ConfigContractApi
 * @contractName: config
 * @contractVersion: 0.1.0
 * @authors: [your_name] <[your_email]>
 * @language: ink! 6.0.0-beta.1
 **/
export interface ConfigContractApi<
  Rv extends RpcVersion = RpcVersion,
  ChainApi extends VersionedGenericSubstrateApi = SubstrateApi,
> extends InkGenericContractApi<Rv, ChainApi> {
  metadataType: 'ink';
  query: ContractQuery<ChainApi[Rv], 'ink'>;
  tx: ContractTx<ChainApi[Rv], 'ink'>;
  constructorQuery: ConstructorQuery<ChainApi[Rv], 'ink'>;
  constructorTx: ConstructorTx<ChainApi[Rv], ConfigContractApi, 'ink'>;
  events: ContractEvents<ChainApi[Rv], 'ink'>;
  storage: {
    root(): Promise<Config>;
    lazy(): WithLazyStorage<Config>;
  };

  types: {
    ChainApi: ChainApi[Rv];
    RootStorage: Config;
    LazyStorage: WithLazyStorage<Config>;
    LangError: InkPrimitivesLangError;
  };
}
