// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result, H160 } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from 'dedot/contracts';
import type { ConfigError, InkPrimitivesLangError } from './types.js';

export interface ContractQuery<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractQuery<ChainApi, Type> {
  /**
   * Setter functions for configuration parameters
   *
   * @param {number} newMin
   * @param {ContractCallOptions} options
   *
   * @selector 0x438c66d1
   **/
  setMinLenders: GenericContractQueryCall<
    ChainApi,
    (
      newMin: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], ConfigError>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {bigint} newFactor
   * @param {ContractCallOptions} options
   *
   * @selector 0x705989b2
   **/
  setOverfundingFactor: GenericContractQueryCall<
    ChainApi,
    (
      newFactor: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], ConfigError>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {bigint} newRate
   * @param {ContractCallOptions} options
   *
   * @selector 0xe7ce83e9
   **/
  setBaseInterestRate: GenericContractQueryCall<
    ChainApi,
    (
      newRate: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], ConfigError>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {bigint} newRate
   * @param {ContractCallOptions} options
   *
   * @selector 0x60f39650
   **/
  setLatePenaltyRate: GenericContractQueryCall<
    ChainApi,
    (
      newRate: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], ConfigError>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   *
   * @param {bigint} newDuration
   * @param {ContractCallOptions} options
   *
   * @selector 0x5eed23cc
   **/
  setMaxLoanDuration: GenericContractQueryCall<
    ChainApi,
    (
      newDuration: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], ConfigError>, ContractCallResult<ChainApi>>>,
    Type
  >;

  /**
   * Getter function for configuration parameters
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x54aca0e4
   **/
  getProtocolInfo: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<[number, bigint, bigint, bigint, bigint, H160], ContractCallResult<ChainApi>>
    >,
    Type
  >;
}
