// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ContractTx<ChainApi extends GenericSubstrateApi, Type extends MetadataType>
  extends GenericContractTx<ChainApi, Type> {
  /**
   * Setter functions for configuration parameters
   *
   * @param {number} newMin
   * @param {ContractTxOptions} options
   *
   * @selector 0x438c66d1
   **/
  setMinLenders: GenericContractTxCall<
    ChainApi,
    (newMin: number, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   *
   * @param {bigint} newFactor
   * @param {ContractTxOptions} options
   *
   * @selector 0x705989b2
   **/
  setOverfundingFactor: GenericContractTxCall<
    ChainApi,
    (newFactor: bigint, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   *
   * @param {bigint} newRate
   * @param {ContractTxOptions} options
   *
   * @selector 0xe7ce83e9
   **/
  setBaseInterestRate: GenericContractTxCall<
    ChainApi,
    (newRate: bigint, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   *
   * @param {bigint} newRate
   * @param {ContractTxOptions} options
   *
   * @selector 0x60f39650
   **/
  setLatePenaltyRate: GenericContractTxCall<
    ChainApi,
    (newRate: bigint, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;

  /**
   *
   * @param {bigint} newDuration
   * @param {ContractTxOptions} options
   *
   * @selector 0x5eed23cc
   **/
  setMaxLoanDuration: GenericContractTxCall<
    ChainApi,
    (newDuration: bigint, options?: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>,
    Type
  >;
}
