// Generated by dedot cli

import type { H160 } from 'dedot/codecs';

export type Config = {
  minLenders: number;
  overfundingFactor: bigint;
  baseInterestRate: bigint;
  latePenaltyRate: bigint;
  maxLoanDuration: bigint;
  admin: H160;
};

export type InkPrimitivesLangError = 'CouldNotReadInput';

export type ConfigError = 'NotAdmin';
